name: Tests

on:
  push:
    branches: [trunk]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: composer install
        run: composer install --no-interaction --no-progress

      - name: Start wp-env
        run: npx wp-env start

      - name: Run PHPUnit (in wp-env)
        run: composer test:env
